# Generated by Django 4.0.6 on 2022-10-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=32)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('gewijzigd', models.DateTimeField(auto_now=True)),
                ('arch', models.BooleanField(default=False)),
                ('melding', models.TextField(blank=True)),
                ('oorzaak', models.TextField(blank=True)),
                ('oplossing', models.TextField(blank=True)),
                ('vervolg', models.TextField(blank=True)),
                ('behandelaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actienemer', to=settings.AUTH_USER_MODEL)),
                ('lasteditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=8)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=80)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='SortOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField()),
                ('volgnr', models.PositiveSmallIntegerField()),
                ('veldnm', models.CharField(max_length=16)),
                ('richting', models.CharField(choices=[('asc', 'oplopend'), ('desc', 'aflopend')], max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Soort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=1, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soort', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField()),
                ('veldnm', models.CharField(max_length=16)),
                ('operator', models.CharField(choices=[('LT', 'kleiner dan'), ('GT', 'groter dan'), ('EQ', 'gelijk aan'), ('NE', 'ongelijk aan'), ('INCL', 'bevat'), ('EXCL', 'bevat niet')], max_length=4)),
                ('extra', models.CharField(choices=[('  ', '  '), ('EN', 'en'), ('OF', 'of')], max_length=2)),
                ('value', models.CharField(max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('actie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.actie')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actie',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acties', to='tracker.project'),
        ),
        migrations.AddField(
            model_name='actie',
            name='soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.soort'),
        ),
        migrations.AddField(
            model_name='actie',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actiehouder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actie',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.status'),
        ),
    ]
