# Generated by Django 4.2.11 on 2024-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_project_assigned_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soort',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='soort',
            name='value',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
